# Generated by Django 3.2.7 on 2022-07-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diary',
        ),
    ]
